version: '2'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  angular:
    build:
      context: SensorsFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - django
