# Generated by Django 2.0.6 on 2018-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sensor', models.CharField(max_length=150)),
                ('acquisition_date', models.DateField(verbose_name='acquisition date')),
                ('signal_type', models.CharField(max_length=150)),
                ('reading_value', models.FloatField(default=0.0)),
                ('reading_date', models.DateField(verbose_name='reading date')),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfiguration',
            fields=[
                ('id_signal', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('signal_type', models.CharField(choices=[('count', 'count'), ('mean', 'mean'), ('median', 'median'), ('min', 'min'), ('max', 'max'), ('std', 'std'), ('var', 'var'), ('mad', 'mad'), ('prod', 'prod'), ('sum', 'sum')], default='mean', max_length=5)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('id_sensor', 'reading_date', 'signal_type')},
        ),
    ]
